name: Fetch News
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Debug Environment
        run: |
          echo "Key exists: ${{ secrets.NEWS_API_KEY != '' }}"
          echo "Key length: ${#NEWS_API_KEY}"
          
      - name: Fetch and Update News
        run: |
          if [ ${#NEWS_API_KEY} -ne 32 ]; then
            echo "Error: API key length is not 32 characters"
            exit 1
          fi
          node .github/scripts/fetch-news.js
          
      - name: Commit and Push
        if: success()
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/news.json
          git commit -m "Update news data" || exit 0
          git push
